In [197]:
%run BlakeFunctions.py

In [198]:
from sage.all import *

In [167]:
#print(qtCat(6))
A = qtCatMat(6)
np.set_printoptions(threshold=np.inf)
print(A)
print(type(A))
print(sum(A))
print(np.prod(A))
print(A[1,1])
np.set_printoptions(threshold=1000)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 3. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 3. 3. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 4. 3. 2. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 3. 4. 3. 2. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 3. 4. 3. 2. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 3. 4. 3. 2. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 2. 3. 3. 2. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 2. 2. 2. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
132.0
0.0
1.0


In [ ]:
vecs = dyckVectors(4)
for vec in vecs:
    DyckWord(area_sequence=vec).pretty_print()
    print("Area: ",dyckArea(vec))
    print("Dinv: ",dyckDinv(vec))
    print("Area Vector: ", vec)
    print('-------------------------')

In [195]:
#print(qtCatMat(7))
#print(qtCatMat(8))
#print(f"n = {7}: number of bijections = {numPossibleBijections(7)}") 

for i in range(1,11):
    print(f"n = {i}: number of bijections = {numPossibleBijections(i)}")    

n = 1: number of bijections = 1
n = 2: number of bijections = 1
n = 3: number of bijections = 1
n = 4: number of bijections = 1
n = 5: number of bijections = 16
n = 6: number of bijections = 165112971264
n = 7: number of bijections = 7081067777179913483347996561235301491807900639024696524800000000000000000000
n = 8: number of bijections = 109229291365542583204089907547123039416111161100155339436116416656121573470362970539442720434107237548881605105751630576212428846557306971114511858523642061693843596909772325458276849998948927558935199685800132163563222008333011111924292501839072087471481906377241532956376752271912959266954639915949483950688990688094475110685081600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
n = 9: number of bijections = 2973111865625474724750012234140294132477967408256872858078543516043790268320565167949589400478070597991752729127735944399721745371914975047583237632286315354327558194825055793504515714765850744

In [211]:
import random
random.seed(int(42))
#bijection = randomBijection(4)
#print(bijection)
#for i in range(len(bijection)):
#    for j in range(len(bijection[i])):
#        bijection[i][j] = DyckWord(area_sequence=bijection[i][j])
#print(bijection)
#bijection2 = randomBijection(6)

for n in range(6,11):
    for k in range(1,11):
        # Create filename like: list_1.txt, list_2.txt, etc.
        bijection = randomBijection(n)
        filename = f"randomBijection_{k}_nEquals_{n}_areaSequence.txt"
        # Write list to file
        with open(filename, 'w') as file:
            file.write('\n'.join(map(str, bijection)))
        # Change the area sequence to a 0,1 sequence
        for i in range(len(bijection)):
            for j in range(len(bijection[i])):
                bijection[i][j] = DyckWord(area_sequence=bijection[i][j])
        filename = f"randomBijection_{k}_nEquals_{n}.txt"
        with open(filename, 'w') as file:
            file.write('\n'.join(map(str, bijection)))

'''
for pair in bijection:
    DyckWord(area_sequence=pair[0]).pretty_print()
    DyckWord(area_sequence=pair[1]).pretty_print()
    print('--------------------')
'''

"\nfor pair in bijection:\n    DyckWord(area_sequence=pair[0]).pretty_print()\n    DyckWord(area_sequence=pair[1]).pretty_print()\n    print('--------------------')\n"

In [ ]:
paired_elements = dyckPairing(5)

# Display paired elements, there should be no unpaired elements due to q,t-symmetry
for pair in paired_elements:
    print(f"Pair: {pair}")
    DyckWord(area_sequence=pair[0]['dyckVec']).pretty_print()
    DyckWord(area_sequence=pair[1]['dyckVec']).pretty_print()
    print('--------------------')

In [ ]:
for i in range(1, 11):
    print("n: ",i)
    print("Percent Nondeterministic: ",percentNondeterministic(int(i)))
    print("--------------------------")